version: '3.7'

services:
  mediastore-database:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: mediastore-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: mediastoreRoo7t0lk2o20
      MYSQL_DATABASE: mediastore_db
      MYSQL_USER: mediastore
      MYSQL_PASSWORD: mediastoret0lk2o20
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongoRepository:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hasan
      MONGO_INITDB_ROOT_PASSWORD: 12345678

  mongo-express:
    image: mongo-express
    ports:
      - 27018:27018
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hasan
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
      ME_CONFIG_MONGODB_URL: mongodb://hasan:12345678@mongoRepository:27017/

volumes:
  dbdata:
