version: '3.7'

services:
  mediastore-database:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: mediastore-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: mediastoreRoo7t0lk2o20
      MYSQL_DATABASE: mediastore_db
      MYSQL_USER: mediastore
      MYSQL_PASSWORD: mediastoret0lk2o20


volumes:
  dbdata:
